name: Keep Repository Alive

on:
  schedule:
    - cron: '0 3 * * 1'  # Every Monday at 03:00 UTC

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update timestamp file
        run: |
          echo "Last update: $(date -u)" > .last_keepalive
          git config --global user.name "keepalive-bot"
          git config --global user.email "keepalive@github"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}
          git add .last_keepalive
          git commit -m "chore: keepalive ping" || echo "No changes to commit"
          git push
